### ISSUE TITLE
Differences between slither & rattle

### ISSUE THREAD

**Issue by wishucry** [crytic/rattle#28]
I am wondering what differences between slither & rattle, from a development and functional point of view?
Thanks a lot!

**Comment by woodruffw** [comment]
Slither takes source code and compiles it, while Rattle does static analysis on decompiled and EVM bytecode. In general, you probably want Slither -- it's stable and actively maintained, while Rattle was an internal research initiative that doesn't receive as much attention.

**Comment by wishucry** [comment]
Thank you so much for your reply!!
Your team has a lot of tools for blockchain security: slither, manticore, rattle, evm_cfg_builder... So I wonder which is the best roadmap for  beginners to learn contract code (especially bytecode) automatic analysis and vul detection. 
I feel very sorry about putting this question here...
